/**
 * Reporting
 * Clearswift Reporting Service API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ActiveDocument model module.
* @module model/ActiveDocument
* @version 1.0.0
*/
export default class ActiveDocument {
    /**
    * Constructs a new <code>ActiveDocument</code>.
    * @alias module:model/ActiveDocument
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ActiveDocument</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ActiveDocument} obj Optional instance to populate.
    * @return {module:model/ActiveDocument} The populated <code>ActiveDocument</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActiveDocument();

            
            
            

            if (data.hasOwnProperty('documentId')) {
                obj['documentId'] = ApiClient.convertToType(data['documentId'], 'Number');
            }
            if (data.hasOwnProperty('documentName')) {
                obj['documentName'] = ApiClient.convertToType(data['documentName'], 'String');
            }
            if (data.hasOwnProperty('documentOwner')) {
                obj['documentOwner'] = ApiClient.convertToType(data['documentOwner'], 'String');
            }
            if (data.hasOwnProperty('registeredTime')) {
                obj['registeredTime'] = ApiClient.convertToType(data['registeredTime'], 'Date');
            }
            if (data.hasOwnProperty('hitCount')) {
                obj['hitCount'] = ApiClient.convertToType(data['hitCount'], 'Number');
            }
            if (data.hasOwnProperty('lastHit')) {
                obj['lastHit'] = ApiClient.convertToType(data['lastHit'], 'Date');
            }
            if (data.hasOwnProperty('classification')) {
                obj['classification'] = ApiClient.convertToType(data['classification'], 'String');
            }
            if (data.hasOwnProperty('classificationLevel')) {
                obj['classificationLevel'] = ApiClient.convertToType(data['classificationLevel'], 'Number');
            }
            if (data.hasOwnProperty('collection')) {
                obj['collection'] = ApiClient.convertToType(data['collection'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} documentId
    */
    documentId = undefined;
    /**
    * @member {String} documentName
    */
    documentName = undefined;
    /**
    * @member {String} documentOwner
    */
    documentOwner = undefined;
    /**
    * @member {Date} registeredTime
    */
    registeredTime = undefined;
    /**
    * @member {Number} hitCount
    */
    hitCount = undefined;
    /**
    * @member {Date} lastHit
    */
    lastHit = undefined;
    /**
    * @member {String} classification
    */
    classification = undefined;
    /**
    * @member {Number} classificationLevel
    */
    classificationLevel = undefined;
    /**
    * @member {String} collection
    */
    collection = undefined;








}


