/**
 * Reporting
 * Clearswift Reporting Service API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MatchType from './MatchType';

/**
 * The DocumentMatch model module.
 * @module model/DocumentMatch
 * @version 1.0.0
 */
class DocumentMatch {
    /**
     * Constructs a new <code>DocumentMatch</code>.
     * @alias module:model/DocumentMatch
     */
    constructor() { 
        
        DocumentMatch.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DocumentMatch</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DocumentMatch} obj Optional instance to populate.
     * @return {module:model/DocumentMatch} The populated <code>DocumentMatch</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DocumentMatch();

            if (data.hasOwnProperty('matchTime')) {
                obj['matchTime'] = ApiClient.convertToType(data['matchTime'], 'Date');
            }
            if (data.hasOwnProperty('matchType')) {
                obj['matchType'] = MatchType.constructFromObject(data['matchType']);
            }
            if (data.hasOwnProperty('origin')) {
                obj['origin'] = ApiClient.convertToType(data['origin'], 'String');
            }
            if (data.hasOwnProperty('target')) {
                obj['target'] = ApiClient.convertToType(data['target'], 'String');
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
            }
            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('transferMode')) {
                obj['transferMode'] = ApiClient.convertToType(data['transferMode'], 'String');
            }
            if (data.hasOwnProperty('direction')) {
                obj['direction'] = ApiClient.convertToType(data['direction'], 'String');
            }
            if (data.hasOwnProperty('sourceName')) {
                obj['sourceName'] = ApiClient.convertToType(data['sourceName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} matchTime
 */
DocumentMatch.prototype['matchTime'] = undefined;

/**
 * @member {module:model/MatchType} matchType
 */
DocumentMatch.prototype['matchType'] = undefined;

/**
 * @member {String} origin
 */
DocumentMatch.prototype['origin'] = undefined;

/**
 * @member {String} target
 */
DocumentMatch.prototype['target'] = undefined;

/**
 * @member {String} subject
 */
DocumentMatch.prototype['subject'] = undefined;

/**
 * @member {String} action
 */
DocumentMatch.prototype['action'] = undefined;

/**
 * @member {String} transferMode
 */
DocumentMatch.prototype['transferMode'] = undefined;

/**
 * @member {String} direction
 */
DocumentMatch.prototype['direction'] = undefined;

/**
 * @member {String} sourceName
 */
DocumentMatch.prototype['sourceName'] = undefined;






export default DocumentMatch;

