/**
 * Reporting
 * Clearswift Reporting Service API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MatchType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MatchType'));
  } else {
    // Browser globals (root is window)
    if (!root.Reporting) {
      root.Reporting = {};
    }
    root.Reporting.DocumentMatch = factory(root.Reporting.ApiClient, root.Reporting.MatchType);
  }
}(this, function(ApiClient, MatchType) {
  'use strict';




  /**
   * The DocumentMatch model module.
   * @module model/DocumentMatch
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>DocumentMatch</code>.
   * @alias module:model/DocumentMatch
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>DocumentMatch</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentMatch} obj Optional instance to populate.
   * @return {module:model/DocumentMatch} The populated <code>DocumentMatch</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('matchTime')) {
        obj['matchTime'] = ApiClient.convertToType(data['matchTime'], 'Date');
      }
      if (data.hasOwnProperty('matchType')) {
        obj['matchType'] = MatchType.constructFromObject(data['matchType']);
      }
      if (data.hasOwnProperty('origin')) {
        obj['origin'] = ApiClient.convertToType(data['origin'], 'String');
      }
      if (data.hasOwnProperty('target')) {
        obj['target'] = ApiClient.convertToType(data['target'], 'String');
      }
      if (data.hasOwnProperty('subject')) {
        obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
      }
      if (data.hasOwnProperty('action')) {
        obj['action'] = ApiClient.convertToType(data['action'], 'String');
      }
      if (data.hasOwnProperty('transferMode')) {
        obj['transferMode'] = ApiClient.convertToType(data['transferMode'], 'String');
      }
      if (data.hasOwnProperty('direction')) {
        obj['direction'] = ApiClient.convertToType(data['direction'], 'String');
      }
      if (data.hasOwnProperty('sourceName')) {
        obj['sourceName'] = ApiClient.convertToType(data['sourceName'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Date} matchTime
   */
  exports.prototype['matchTime'] = undefined;
  /**
   * @member {module:model/MatchType} matchType
   */
  exports.prototype['matchType'] = undefined;
  /**
   * @member {String} origin
   */
  exports.prototype['origin'] = undefined;
  /**
   * @member {String} target
   */
  exports.prototype['target'] = undefined;
  /**
   * @member {String} subject
   */
  exports.prototype['subject'] = undefined;
  /**
   * @member {String} action
   */
  exports.prototype['action'] = undefined;
  /**
   * @member {String} transferMode
   */
  exports.prototype['transferMode'] = undefined;
  /**
   * @member {String} direction
   */
  exports.prototype['direction'] = undefined;
  /**
   * @member {String} sourceName
   */
  exports.prototype['sourceName'] = undefined;



  return exports;
}));


