/**
 * Reporting
 * Clearswift Reporting Service API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import MatchType from './MatchType';





/**
* The DocumentMatch model module.
* @module model/DocumentMatch
* @version 1.0.0
*/
export default class DocumentMatch {
    /**
    * Constructs a new <code>DocumentMatch</code>.
    * @alias module:model/DocumentMatch
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>DocumentMatch</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DocumentMatch} obj Optional instance to populate.
    * @return {module:model/DocumentMatch} The populated <code>DocumentMatch</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DocumentMatch();

            
            
            

            if (data.hasOwnProperty('matchTime')) {
                obj['matchTime'] = ApiClient.convertToType(data['matchTime'], 'Date');
            }
            if (data.hasOwnProperty('matchType')) {
                obj['matchType'] = MatchType.constructFromObject(data['matchType']);
            }
            if (data.hasOwnProperty('origin')) {
                obj['origin'] = ApiClient.convertToType(data['origin'], 'String');
            }
            if (data.hasOwnProperty('target')) {
                obj['target'] = ApiClient.convertToType(data['target'], 'String');
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
            }
            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('transferMode')) {
                obj['transferMode'] = ApiClient.convertToType(data['transferMode'], 'String');
            }
            if (data.hasOwnProperty('direction')) {
                obj['direction'] = ApiClient.convertToType(data['direction'], 'String');
            }
            if (data.hasOwnProperty('sourceName')) {
                obj['sourceName'] = ApiClient.convertToType(data['sourceName'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Date} matchTime
    */
    matchTime = undefined;
    /**
    * @member {module:model/MatchType} matchType
    */
    matchType = undefined;
    /**
    * @member {String} origin
    */
    origin = undefined;
    /**
    * @member {String} target
    */
    target = undefined;
    /**
    * @member {String} subject
    */
    subject = undefined;
    /**
    * @member {String} action
    */
    action = undefined;
    /**
    * @member {String} transferMode
    */
    transferMode = undefined;
    /**
    * @member {String} direction
    */
    direction = undefined;
    /**
    * @member {String} sourceName
    */
    sourceName = undefined;








}


