/**
 * Reporting
 * Clearswift Reporting Service API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DocumentMatch from './DocumentMatch';
import RegisteredDocument from './RegisteredDocument';

/**
 * The DocumentDetail model module.
 * @module model/DocumentDetail
 * @version 1.0.0
 */
class DocumentDetail {
    /**
     * Constructs a new <code>DocumentDetail</code>.
     * @alias module:model/DocumentDetail
     */
    constructor() { 
        
        DocumentDetail.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DocumentDetail</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DocumentDetail} obj Optional instance to populate.
     * @return {module:model/DocumentDetail} The populated <code>DocumentDetail</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DocumentDetail();

            if (data.hasOwnProperty('registeredDocument')) {
                obj['registeredDocument'] = RegisteredDocument.constructFromObject(data['registeredDocument']);
            }
            if (data.hasOwnProperty('documentMatches')) {
                obj['documentMatches'] = ApiClient.convertToType(data['documentMatches'], [DocumentMatch]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/RegisteredDocument} registeredDocument
 */
DocumentDetail.prototype['registeredDocument'] = undefined;

/**
 * @member {Array.<module:model/DocumentMatch>} documentMatches
 */
DocumentDetail.prototype['documentMatches'] = undefined;






export default DocumentDetail;

