/**
 * Reporting
 * Clearswift Reporting Service API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Reporting) {
      root.Reporting = {};
    }
    root.Reporting.DocumentActivity = factory(root.Reporting.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DocumentActivity model module.
   * @module model/DocumentActivity
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>DocumentActivity</code>.
   * @alias module:model/DocumentActivity
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>DocumentActivity</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentActivity} obj Optional instance to populate.
   * @return {module:model/DocumentActivity} The populated <code>DocumentActivity</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('documentId')) {
        obj['documentId'] = ApiClient.convertToType(data['documentId'], 'Number');
      }
      if (data.hasOwnProperty('documentName')) {
        obj['documentName'] = ApiClient.convertToType(data['documentName'], 'String');
      }
      if (data.hasOwnProperty('documentOwner')) {
        obj['documentOwner'] = ApiClient.convertToType(data['documentOwner'], 'String');
      }
      if (data.hasOwnProperty('registeredTime')) {
        obj['registeredTime'] = ApiClient.convertToType(data['registeredTime'], 'Date');
      }
      if (data.hasOwnProperty('hitCount')) {
        obj['hitCount'] = ApiClient.convertToType(data['hitCount'], 'Number');
      }
      if (data.hasOwnProperty('lastHit')) {
        obj['lastHit'] = ApiClient.convertToType(data['lastHit'], 'Date');
      }
      if (data.hasOwnProperty('classification')) {
        obj['classification'] = ApiClient.convertToType(data['classification'], 'String');
      }
      if (data.hasOwnProperty('classificationLevel')) {
        obj['classificationLevel'] = ApiClient.convertToType(data['classificationLevel'], 'Number');
      }
      if (data.hasOwnProperty('collection')) {
        obj['collection'] = ApiClient.convertToType(data['collection'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} documentId
   */
  exports.prototype['documentId'] = undefined;
  /**
   * @member {String} documentName
   */
  exports.prototype['documentName'] = undefined;
  /**
   * @member {String} documentOwner
   */
  exports.prototype['documentOwner'] = undefined;
  /**
   * @member {Date} registeredTime
   */
  exports.prototype['registeredTime'] = undefined;
  /**
   * @member {Number} hitCount
   */
  exports.prototype['hitCount'] = undefined;
  /**
   * @member {Date} lastHit
   */
  exports.prototype['lastHit'] = undefined;
  /**
   * @member {String} classification
   */
  exports.prototype['classification'] = undefined;
  /**
   * @member {Number} classificationLevel
   */
  exports.prototype['classificationLevel'] = undefined;
  /**
   * @member {String} collection
   */
  exports.prototype['collection'] = undefined;



  return exports;
}));


