/**
 * Reporting
 * Clearswift Reporting Service API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DocumentsByUser model module.
 * @module model/DocumentsByUser
 * @version 1.0.0
 */
class DocumentsByUser {
    /**
     * Constructs a new <code>DocumentsByUser</code>.
     * @alias module:model/DocumentsByUser
     */
    constructor() { 
        
        DocumentsByUser.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DocumentsByUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DocumentsByUser} obj Optional instance to populate.
     * @return {module:model/DocumentsByUser} The populated <code>DocumentsByUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DocumentsByUser();

            if (data.hasOwnProperty('displayName')) {
                obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('upn')) {
                obj['upn'] = ApiClient.convertToType(data['upn'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('documents')) {
                obj['documents'] = ApiClient.convertToType(data['documents'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} displayName
 */
DocumentsByUser.prototype['displayName'] = undefined;

/**
 * @member {String} email
 */
DocumentsByUser.prototype['email'] = undefined;

/**
 * @member {String} upn
 */
DocumentsByUser.prototype['upn'] = undefined;

/**
 * @member {String} role
 */
DocumentsByUser.prototype['role'] = undefined;

/**
 * @member {Array.<String>} documents
 */
DocumentsByUser.prototype['documents'] = undefined;






export default DocumentsByUser;

