/**
 * Reporting
 * Clearswift Reporting Service API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class MatchType.
* @enum {}
* @readonly
*/
export default class MatchType {
    constructor(){
    
        /**
         * value: "FULL"
         * @const
         */
        this.FULL = "FULL";

    
        /**
         * value: "PARTIAL"
         * @const
         */
        this.PARTIAL = "PARTIAL";

    
    }
    /**
    * Returns a <code>MatchType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/MatchType} The enum <code>MatchType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

