/**
 * Reporting
 * Clearswift Reporting Service API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RegisteredDocument model module.
 * @module model/RegisteredDocument
 * @version 1.0.0
 */
class RegisteredDocument {
    /**
     * Constructs a new <code>RegisteredDocument</code>.
     * @alias module:model/RegisteredDocument
     */
    constructor() { 
        
        RegisteredDocument.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RegisteredDocument</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegisteredDocument} obj Optional instance to populate.
     * @return {module:model/RegisteredDocument} The populated <code>RegisteredDocument</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegisteredDocument();

            if (data.hasOwnProperty('documentId')) {
                obj['documentId'] = ApiClient.convertToType(data['documentId'], 'Number');
            }
            if (data.hasOwnProperty('documentName')) {
                obj['documentName'] = ApiClient.convertToType(data['documentName'], 'String');
            }
            if (data.hasOwnProperty('documentOwner')) {
                obj['documentOwner'] = ApiClient.convertToType(data['documentOwner'], 'String');
            }
            if (data.hasOwnProperty('registeredTime')) {
                obj['registeredTime'] = ApiClient.convertToType(data['registeredTime'], 'Date');
            }
            if (data.hasOwnProperty('hitCount')) {
                obj['hitCount'] = ApiClient.convertToType(data['hitCount'], 'Number');
            }
            if (data.hasOwnProperty('lastHit')) {
                obj['lastHit'] = ApiClient.convertToType(data['lastHit'], 'Date');
            }
            if (data.hasOwnProperty('classification')) {
                obj['classification'] = ApiClient.convertToType(data['classification'], 'String');
            }
            if (data.hasOwnProperty('classificationLevel')) {
                obj['classificationLevel'] = ApiClient.convertToType(data['classificationLevel'], 'Number');
            }
            if (data.hasOwnProperty('collection')) {
                obj['collection'] = ApiClient.convertToType(data['collection'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} documentId
 */
RegisteredDocument.prototype['documentId'] = undefined;

/**
 * @member {String} documentName
 */
RegisteredDocument.prototype['documentName'] = undefined;

/**
 * @member {String} documentOwner
 */
RegisteredDocument.prototype['documentOwner'] = undefined;

/**
 * @member {Date} registeredTime
 */
RegisteredDocument.prototype['registeredTime'] = undefined;

/**
 * @member {Number} hitCount
 */
RegisteredDocument.prototype['hitCount'] = undefined;

/**
 * @member {Date} lastHit
 */
RegisteredDocument.prototype['lastHit'] = undefined;

/**
 * @member {String} classification
 */
RegisteredDocument.prototype['classification'] = undefined;

/**
 * @member {Number} classificationLevel
 */
RegisteredDocument.prototype['classificationLevel'] = undefined;

/**
 * @member {String} collection
 */
RegisteredDocument.prototype['collection'] = undefined;






export default RegisteredDocument;

