/**
 * Reporting
 * Clearswift Reporting Service API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Status from './Status';





/**
* The ServiceStatus model module.
* @module model/ServiceStatus
* @version 1.0.0
*/
export default class ServiceStatus {
    /**
    * Constructs a new <code>ServiceStatus</code>.
    * @alias module:model/ServiceStatus
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ServiceStatus</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ServiceStatus} obj Optional instance to populate.
    * @return {module:model/ServiceStatus} The populated <code>ServiceStatus</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceStatus();

            
            
            

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = Status.constructFromObject(data['status']);
            }
        }
        return obj;
    }

    /**
    * @member {String} message
    */
    message = undefined;
    /**
    * @member {module:model/Status} status
    */
    status = undefined;








}


