/**
 * Reporting
 * Clearswift Reporting Service API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Status from './Status';

/**
 * The ServiceStatus model module.
 * @module model/ServiceStatus
 * @version 1.0.0
 */
class ServiceStatus {
    /**
     * Constructs a new <code>ServiceStatus</code>.
     * @alias module:model/ServiceStatus
     */
    constructor() { 
        
        ServiceStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ServiceStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServiceStatus} obj Optional instance to populate.
     * @return {module:model/ServiceStatus} The populated <code>ServiceStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceStatus();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = Status.constructFromObject(data['status']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} message
 */
ServiceStatus.prototype['message'] = undefined;

/**
 * @member {module:model/Status} status
 */
ServiceStatus.prototype['status'] = undefined;






export default ServiceStatus;

