/**
 * Reporting
 * Clearswift Reporting Service API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Reporting) {
      root.Reporting = {};
    }
    root.Reporting.Status = factory(root.Reporting.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class Status.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "HEALTHY"
     * @const
     */
    "HEALTHY": "HEALTHY",
    /**
     * value: "UNHEALTHY"
     * @const
     */
    "UNHEALTHY": "UNHEALTHY"  };

  /**
   * Returns a <code>Status</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/Status} The enum <code>Status</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


