/**
 * Reporting
 * Clearswift Reporting Service API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserDetail model module.
 * @module model/UserDetail
 * @version 1.0.0
 */
class UserDetail {
    /**
     * Constructs a new <code>UserDetail</code>.
     * @alias module:model/UserDetail
     */
    constructor() { 
        
        UserDetail.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserDetail</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserDetail} obj Optional instance to populate.
     * @return {module:model/UserDetail} The populated <code>UserDetail</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserDetail();

            if (data.hasOwnProperty('displayName')) {
                obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('upn')) {
                obj['upn'] = ApiClient.convertToType(data['upn'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('documentName')) {
                obj['documentName'] = ApiClient.convertToType(data['documentName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} displayName
 */
UserDetail.prototype['displayName'] = undefined;

/**
 * @member {String} email
 */
UserDetail.prototype['email'] = undefined;

/**
 * @member {String} upn
 */
UserDetail.prototype['upn'] = undefined;

/**
 * @member {String} role
 */
UserDetail.prototype['role'] = undefined;

/**
 * @member {String} documentName
 */
UserDetail.prototype['documentName'] = undefined;






export default UserDetail;

