/**
 * Reporting
 * Clearswift Reporting Service API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Reporting);
  }
}(this, function(expect, Reporting) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Reporting.ActiveDocument();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ActiveDocument', function() {
    it('should create an instance of ActiveDocument', function() {
      // uncomment below and update the code to test ActiveDocument
      //var instance = new Reporting.ActiveDocument();
      //expect(instance).to.be.a(Reporting.ActiveDocument);
    });

    it('should have the property documentId (base name: "documentId")', function() {
      // uncomment below and update the code to test the property documentId
      //var instance = new Reporting.ActiveDocument();
      //expect(instance).to.be();
    });

    it('should have the property documentName (base name: "documentName")', function() {
      // uncomment below and update the code to test the property documentName
      //var instance = new Reporting.ActiveDocument();
      //expect(instance).to.be();
    });

    it('should have the property documentOwner (base name: "documentOwner")', function() {
      // uncomment below and update the code to test the property documentOwner
      //var instance = new Reporting.ActiveDocument();
      //expect(instance).to.be();
    });

    it('should have the property registeredTime (base name: "registeredTime")', function() {
      // uncomment below and update the code to test the property registeredTime
      //var instance = new Reporting.ActiveDocument();
      //expect(instance).to.be();
    });

    it('should have the property hitCount (base name: "hitCount")', function() {
      // uncomment below and update the code to test the property hitCount
      //var instance = new Reporting.ActiveDocument();
      //expect(instance).to.be();
    });

    it('should have the property lastHit (base name: "lastHit")', function() {
      // uncomment below and update the code to test the property lastHit
      //var instance = new Reporting.ActiveDocument();
      //expect(instance).to.be();
    });

    it('should have the property classification (base name: "classification")', function() {
      // uncomment below and update the code to test the property classification
      //var instance = new Reporting.ActiveDocument();
      //expect(instance).to.be();
    });

    it('should have the property classificationLevel (base name: "classificationLevel")', function() {
      // uncomment below and update the code to test the property classificationLevel
      //var instance = new Reporting.ActiveDocument();
      //expect(instance).to.be();
    });

    it('should have the property collection (base name: "collection")', function() {
      // uncomment below and update the code to test the property collection
      //var instance = new Reporting.ActiveDocument();
      //expect(instance).to.be();
    });

  });

}));
