/**
 * Reporting
 * Clearswift Reporting Service API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Credentials from './model/Credentials';
import DocumentMatch from './model/DocumentMatch';
import DocumentsByUser from './model/DocumentsByUser';
import IgFilter from './model/IgFilter';
import JwtToken from './model/JwtToken';
import MatchType from './model/MatchType';
import RegisteredDocument from './model/RegisteredDocument';
import ServiceStatus from './model/ServiceStatus';
import Status from './model/Status';
import AuthenticationApi from './api/AuthenticationApi';
import IGApi from './api/IGApi';
import ServiceCheckApi from './api/ServiceCheckApi';


/**
* Clearswift_Reporting_Service_API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Reporting = require('index'); // See note below*.
* var xxxSvc = new Reporting.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Reporting.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Reporting.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Reporting.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Credentials model constructor.
     * @property {module:model/Credentials}
     */
    Credentials,

    /**
     * The DocumentMatch model constructor.
     * @property {module:model/DocumentMatch}
     */
    DocumentMatch,

    /**
     * The DocumentsByUser model constructor.
     * @property {module:model/DocumentsByUser}
     */
    DocumentsByUser,

    /**
     * The IgFilter model constructor.
     * @property {module:model/IgFilter}
     */
    IgFilter,

    /**
     * The JwtToken model constructor.
     * @property {module:model/JwtToken}
     */
    JwtToken,

    /**
     * The MatchType model constructor.
     * @property {module:model/MatchType}
     */
    MatchType,

    /**
     * The RegisteredDocument model constructor.
     * @property {module:model/RegisteredDocument}
     */
    RegisteredDocument,

    /**
     * The ServiceStatus model constructor.
     * @property {module:model/ServiceStatus}
     */
    ServiceStatus,

    /**
     * The Status model constructor.
     * @property {module:model/Status}
     */
    Status,

    /**
    * The AuthenticationApi service constructor.
    * @property {module:api/AuthenticationApi}
    */
    AuthenticationApi,

    /**
    * The IGApi service constructor.
    * @property {module:api/IGApi}
    */
    IGApi,

    /**
    * The ServiceCheckApi service constructor.
    * @property {module:api/ServiceCheckApi}
    */
    ServiceCheckApi
};
