/**
 * Reporting
 * Clearswift Reporting Service API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Reporting);
  }
}(this, function(expect, Reporting) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Reporting.IGApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('IGApi', function() {
    describe('igDocumentsByUserPost', function() {
      it('should call igDocumentsByUserPost successfully', function(done) {
        //uncomment below and update the code to test igDocumentsByUserPost
        //instance.igDocumentsByUserPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('igDocumentsIdMatchesGet', function() {
      it('should call igDocumentsIdMatchesGet successfully', function(done) {
        //uncomment below and update the code to test igDocumentsIdMatchesGet
        //instance.igDocumentsIdMatchesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('igDocumentsPost', function() {
      it('should call igDocumentsPost successfully', function(done) {
        //uncomment below and update the code to test igDocumentsPost
        //instance.igDocumentsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('igMatchesPost', function() {
      it('should call igMatchesPost successfully', function(done) {
        //uncomment below and update the code to test igMatchesPost
        //instance.igMatchesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('igUsersIdActiveDocumentsGet', function() {
      it('should call igUsersIdActiveDocumentsGet successfully', function(done) {
        //uncomment below and update the code to test igUsersIdActiveDocumentsGet
        //instance.igUsersIdActiveDocumentsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
